version: '3'

services:
  client:
    image: yolo:v1.0.0
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - ip-network

  backend:
    image: yolo_backend:v1.0.0
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - mongodb
    networks:
      - ip-network
      
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - ip-network

networks:
    ip-network:

volumes:
  mongodb_data:
