---
- name: Deploy Yolo App using Vagrant
  hosts: all
  become: true
  become_user: root

  tasks:

    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Add Docker GPG apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker - ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    
    
    - name: Install Git
      apt:
        name: git
        state: present

    - name: Clone the code from GitHub
      git:
        repo: git@github.com:Musyoki-Wambua/yolo.git
        dest: /home/code/yolo
        version: master  